### PR TITLE
Make rule code optional

### PR DESCRIPTION
**Pull request by mrgleba**

### CODE REVIEW

**Comment by dsyme** [comment]
Could you add a test for this please?

**Comment by mrgleba** [comment]
I've added this to be able to parse a C yacc file, but I need to investigate this a little bit further.
This should've taken care od the "Yacc default action" (generally { $1 }), but it's a bit more complex than just the commit Ive posted.

I'll close for now and reopen in case I arrive at something useful.

**Comment by mrgleba** [comment]
I investigated this a bit further.
I won't be going so far as to add default action functionality.
Still the patch is IMHO advantageous:
 - it's non-breaking: all paresers that compiled befeore will stay the same
 - allows for the code not to be specified - in that case an exception would be raised at runtime

As this allows for a parse to succeed (without generating a meaningful code, but still...) for a wider class of already existring paresers in other languages I would propose fot it to be merged.

As with the test. I can easily provide a grammar that compiles after and not before but I was unable to figure out how things in the test folder work :( I would appreciate some guidance with that.

**Comment by mrgleba** [comment]
In case the action is absent we could do 2 things:
 1) assume { $1 } as is yacc's default
 2) throw an exception when rule is reached: ie { failwith "rule action missing" }
 3) refuse to produce parsed - the current behaviour

I'll update this PR with a command line option that would allow either option 1 or 2 to be chosen over the default behaviour.

**Comment by TorbenMogensen** [comment]
A problem with assuming { $1 } is that it might not be consistent with the declared type.

An idea would be to allow missing actions if the declared type is unit, but otherwise not.  This way, you can develop a grammar without actions by declaring nonterminals to have type unit and then add actions later,

**Comment by mrgleba** [comment]
I've added a comand line option to decide the behaviour.

**Comment by dsyme** [comment]
Throwing in a random idea, I've often thought that FsLexYacc should come with type providers, useful for small grammars and tokenizers

```fsharp
type MyGrammar = YaccProvider<""" .... grammar ...""">

MyGrammar.Parse(source)

type MyTokenizer = LexProvider<""" .... tokenizer ...""">

MyTokenizer.Tokenize(source)
```

The problem is specifying the actions, which are of course F# code. F# type providers don't provide particularly good ways to anti-quote F# code, so the normal thing would be to return an object where you can fill in the holes with code, e.g.

```fsharp

type MyGrammar = YaccProvider<""" .... grammar Action1 Action2 ...""">

let myParser = 
    { new MyGrammar() with 
 .        member x.Action1(item1, item2) = Node1(item1,item2)
 .        member x.Action2(item1, item2) = Node2(item1,item2) 
          ... }

let results = myParser.Parse(source)

```
This would be in addition to the command line tools - so that the core of FsLex and FsYacc would be provided with two different window-dressings - one command line, one type provider

What do you think? Would anyone lie to prototype this functionality?

Cheers
Don

**Comment by mrgleba** [comment]
Few things I noticed thinking about this in FsYacc:

 - we'd have to define explicitely the type of every non-terminal - I can't see a way to do type inference without having the actions (actually this would be hard even with the actions present)

 - AFAIK type providers can't produce abstract classes, so we'd have to use ferlection at run-time. This would give a slight overhead and we won't be able to tell if we provided all the actions before we run the program.

 - compilation sometimes thaes a substantial time, so this type provider would cater only to small projects

 - the biggest issue I can see is there is no easy way to map a grammar rule to the code.

Let's consider:
`
expr:
| VAL // action 1 
| expr PLUS expr  // action 2
`

We have some options:
- require that action contains function name to call at runtime
`
expr:
| VAL { Foo }
| expr PLUS expr { Bar }
`
`
let myParser = 
    { new MyGrammar() with 
          member x.Foo(v) = v
          member x.Bar(v1, v2) = v1 + v2
          ... }
`
This would result in a rather big and not very readable code and the grammar text would have to be redone fom egular fsyacc.

- another option is to ignore acions and make function names more explicit:
`
let myParser = 
    { new MyGrammar() with 
          member x.Expr_VAL(v) = v
          member x.Expr_Expr-PLUS-Expr(v1, v2) = v1 + v2
          ... }
`
The code would still be bloated but now we don't have to alter the grammar.

- yet another option is to provide methods that would take functions in order of rule apperance:
`
let gr = new MyGrammar()
gr.Expr(
 (fun v -> v),
 (fun (v1, v2) -> v2 + v2))
`
This is probably the most sane and we'll get type hints via intelisense. Not very readable though and
prone to hard to catch bugs when adding new rules (a function previousl specified for expr PLUS expr might easli by shifted to be called for expr MINUS expr if a new rule is introduced)

The way I see it:
 - this would require a lot of work
 - the resulting tool would require unreadable code and new ways to introduce hard to catch bugs
 - it would not do anything that could not be achieved with current tools
 - the only benefit is we'd get intelisense a while earlier (prior to invoking fsyacc rather than just after)

I might be missing some obvious solutions here, so I'd gladly hear other the ideas.

**Comment by dsyme** [comment]
Close old PR , apologies this didn't make it in

**Pull request closed without merging**
