### PR TITLE
Fix misc packaging issues

### PR DESCRIPTION
**Pull request by baronfel**
This PR fixes the package relationships to be what @sergey-tihon pointed out in [this comment](https://github.com/fsprojects/FsLexYacc/issues/143#issuecomment-774663948).  We want users of the the tooling to be able to actually _run_ their parsers, so they need a runtime-reference to FsLexYacc.Runtime.

After this, the generated package nuspec looks like

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
  <metadata>
    <id>FsLexYacc</id>
    <version>10.2.0</version>
    <authors>Microsoft Corporation, Don Syme, F# Software Foundation contributors</authors>
    <licenseUrl>https://github.com/fsprojects/FsLexYacc/blob/master/LICENSE.txt</licenseUrl>
    <projectUrl>https://github.com/fsprojects/FsLexYacc</projectUrl>
    <iconUrl>https://raw.githubusercontent.com/fsprojects/FsLexYacc/master/docs/files/img/logo.png</iconUrl>
    <description>Tools for FsLex/FsYacc lexer/parser generation tools</description>
    <summary>Tools for FsLex/FsYacc lexer/parser generation tools</summary>
    <releaseNotes>Enable running tools under .net 5.0</releaseNotes>
    <tags>F# fsharp yacc fsyacc lex parsing lexing fslex</tags>
    <dependencies>
      <dependency id="FsLexYacc.Runtime" version="[10.2.0,10.3.0)" />
      <dependency id="FSharp.Core" version="4.6.2" />
    </dependencies>
  </metadata>
</package>
```

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@baronfel do you prefer to have this fix merged or continue working on other packaging issues here ?

**Comment by baronfel** [comment]
Oh I'll fix up the inadvertent dependnecy that FsLex.Core has on FsLexYacc as well here.

**Comment by baronfel** [comment]
Alright, fixes FsLex.Core as well. The new nuspec is:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>FsLex.Core</id>
    <version>1.0.0</version>
    <authors>Microsoft Corporation, Don Syme, F# Software Foundation contributors</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>
    <icon>logo.png</icon>
    <projectUrl>https://github.com/fsprojects/FsLexYacc</projectUrl>
    <iconUrl>https://raw.githubusercontent.com/fsprojects/FsLexYacc/master/docs/files/img/logo.png</iconUrl>
    <description>Package Description</description>
    <tags>F#, fsharp, yacc, fsyacc, lex, parsing, lexing, fslex</tags>
    <repository type="git" url="https://github.com/baronfel/FsLexYacc" commit="c2b8f9706446ef0f70acfe957e0760c2999fa494" />
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="FSharp.Core" version="4.6.2" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by baronfel** [comment]
the only outstanding thing here is that the fslex.core and fsyacc.core packages need a dependency on FsLexYacc.Runtime, since they expose types like Position that exist in that library.

**Comment by sergey-tihon** [comment]
Do you know how to do it with `dotnet pack` or we need to pack with `paket`?

**Comment by baronfel** [comment]
Paket should handle allowing project references to flow through the nuspec (at least according to the discussion [here](https://github.com/fsprojects/Paket/issues/2694)), but I think we're hitting a bug here due to the circular nature of our dependencies for the fslex.core and fsyacc.core projects:

* they both _use_ fslexyacc as a dev dependency, which implicitly brings in the FsLexYacc.Runtime transitive dependency.
* they both _also_ have a project dependency on FsLexYacc.Runtime (which ideally would be left untouched by paket)
* the initial nuspec created by `dotnet pack` includes the project reference, translated to a package reference
* `paket fix-nuspecs` removes this reference, possibly because it sees that the transitive reference isn't a top-level package reference, even though this is a project-reference

**Comment by baronfel** [comment]
I've submitted a draft PR to paket to fix this behavior. Once that's addressed we can update our version of paket and this PR should 'just work'.

**Comment by baronfel** [comment]
Ok, updated Paket to pick up the bugfix I got merged into that project.  The nuspec for FsLexYacc now looks like this:

```
➜  fslexyaccpkg git:(fslexyacc-runtime-dependency) ✗ cat FsLexYacc.nuspec 
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: FsLexYacc.nuspec
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ <?xml version="1.0" encoding="utf-8" standalone="yes"?>
   2   │ <package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
   3   │   <metadata>
   4   │     <id>FsLexYacc</id>
   5   │     <version>10.2.0</version>
   6   │     <authors>Microsoft Corporation, Don Syme, F# Software Foundation contributors</authors>
   7   │     <licenseUrl>https://github.com/fsprojects/FsLexYacc/blob/master/LICENSE.txt</licenseUrl>
   8   │     <projectUrl>https://github.com/fsprojects/FsLexYacc</projectUrl>
   9   │     <iconUrl>https://raw.githubusercontent.com/fsprojects/FsLexYacc/master/docs/files/img/logo.png</iconUrl>
  10   │     <description>Tools for FsLex/FsYacc lexer/parser generation tools</description>
  11   │     <summary>Tools for FsLex/FsYacc lexer/parser generation tools</summary>
  12   │     <releaseNotes>Enable running tools under .net 5.0</releaseNotes>
  13   │     <tags>F# fsharp yacc fsyacc lex parsing lexing fslex</tags>
  14   │     <dependencies>
  15   │       <dependency id="FsLexYacc.Runtime" version="[10.2.0,10.3.0)" />
  16   │       <dependency id="FSharp.Core" version="4.6.2" />
  17   │     </dependencies>
  18   │   </metadata>
  19   │ </package>

```

which looks sane to me.

The fslex.core and fsyacc.core package similarly have the FsLexYacc.Runtime dependency added now:

```
➜  bin git:(fslexyacc-runtime-dependency) ✗ cat fslexcorepkg/FsLex.Core.nuspec
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: fslexcorepkg/FsLex.Core.nuspec
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ <?xml version="1.0" encoding="utf-8"?>
   2   │ <package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
   3   │   <metadata>
   4   │     <id>FsLex.Core</id>
   5   │     <version>10.2.0</version>
   6   │     <authors>Microsoft Corporation, Don Syme, F# Software Foundation contributors</authors>
   7   │     <requireLicenseAcceptance>false</requireLicenseAcceptance>
   8   │     <license type="expression">MIT</license>
   9   │     <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>
  10   │     <icon>logo.png</icon>
  11   │     <projectUrl>https://github.com/fsprojects/FsLexYacc</projectUrl>
  12   │     <iconUrl>https://raw.githubusercontent.com/fsprojects/FsLexYacc/master/docs/files/img/logo.png</iconUrl>
  13   │     <description>Package Description</description>
  14   │     <releaseNotes>Enable running tools under .net 5.0</releaseNotes>
  15   │     <tags>F#, fsharp, yacc, fsyacc, lex, parsing, lexing, fslex</tags>
  16   │     <repository type="git" url="https://github.com/baronfel/FsLexYacc" commit="e3317a9a8345ab9e5768b829fa1854cf6f1388e
       │ 3" />
  17   │     <dependencies>
  18   │       <group targetFramework=".NETStandard2.0">
  19   │         <dependency id="FsLexYacc.Runtime" version="10.2.0" exclude="Build,Analyzers" />
  20   │         <dependency id="FSharp.Core" version="4.6.2" exclude="Build,Analyzers" />
  21   │       </group>
  22   │     </dependencies>
  23   │   </metadata>
  24   │ </package>
```

So I think we're ok there, too.

**Comment by baronfel** [comment]
layout of fslexyacc package:

```
➜  fslexyaccpkg git:(fslexyacc-runtime-dependency) ✗ tree .
.
├── FsLexYacc.nuspec
├── [Content_Types].xml
├── _rels
├── build
│   ├── FsLexYacc.targets
│   ├── fslex
│   │   └── netcoreapp3.1
│   │       ├── FSharp.Core.dll
│   │       ├── FsLex.Core.dll
│   │       ├── FsLex.Core.pdb
│   │       ├── FsLex.Core.xml
│   │       ├── FsLexYacc.Runtime.dll
│   │       ├── FsLexYacc.Runtime.pdb
│   │       ├── FsLexYacc.Runtime.xml
│   │       ├── cs
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── de
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── en
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── es
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── fr
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── fslex.deps.json
│   │       ├── fslex.dll
│   │       ├── fslex.pdb
│   │       ├── fslex.runtimeconfig.json
│   │       ├── fslex.xml
│   │       ├── it
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── ja
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── ko
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── pl
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── pt-BR
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── ru
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── tr
│   │       │   └── FSharp.Core.resources.dll
│   │       ├── zh-Hans
│   │       │   └── FSharp.Core.resources.dll
│   │       └── zh-Hant
│   │           └── FSharp.Core.resources.dll
│   └── fsyacc
│       └── netcoreapp3.1
│           ├── FSharp.Core.dll
│           ├── FsLexYacc.Runtime.dll
│           ├── FsLexYacc.Runtime.pdb
│           ├── FsLexYacc.Runtime.xml
│           ├── FsLexYacc.targets
│           ├── FsYacc.Core.dll
│           ├── FsYacc.Core.pdb
│           ├── FsYacc.Core.xml
│           ├── cs
│           │   └── FSharp.Core.resources.dll
│           ├── de
│           │   └── FSharp.Core.resources.dll
│           ├── en
│           │   └── FSharp.Core.resources.dll
│           ├── es
│           │   └── FSharp.Core.resources.dll
│           ├── fr
│           │   └── FSharp.Core.resources.dll
│           ├── fsyacc.deps.json
│           ├── fsyacc.dll
│           ├── fsyacc.pdb
│           ├── fsyacc.runtimeconfig.json
│           ├── fsyacc.xml
│           ├── it
│           │   └── FSharp.Core.resources.dll
│           ├── ja
│           │   └── FSharp.Core.resources.dll
│           ├── ko
│           │   └── FSharp.Core.resources.dll
│           ├── pl
│           │   └── FSharp.Core.resources.dll
│           ├── pt-BR
│           │   └── FSharp.Core.resources.dll
│           ├── ru
│           │   └── FSharp.Core.resources.dll
│           ├── tr
│           │   └── FSharp.Core.resources.dll
│           ├── zh-Hans
│           │   └── FSharp.Core.resources.dll
│           └── zh-Hant
│               └── FSharp.Core.resources.dll
├── package
│   └── services
│       └── metadata
│           └── core-properties
│               └── coreProp.psmdcp
└── src
    ├── FsLexYacc.targets
    ├── fslex
    │   ├── Arg.fs
    │   ├── Arg.fsi
    │   ├── Lexing.fs
    │   ├── Lexing.fsi
    │   ├── Parsing.fs
    │   ├── Parsing.fsi
    │   ├── fslex.fs
    │   ├── fslex.fsx
    │   ├── fslexast.fs
    │   ├── fslexlex.fs
    │   └── fslexpars.fs
    └── fsyacc
        ├── Arg.fs
        ├── Arg.fsi
        ├── Lexing.fs
        ├── Lexing.fsi
        ├── Parsing.fs
        ├── Parsing.fsi
        ├── fsyacc.fs
        ├── fsyacc.fsx
        ├── fsyaccast.fs
        ├── fsyacclex.fs
        └── fsyaccpars.fs

41 directories, 80 files

```

This has no lib folders, only the sourcelinked source and the runtime binaries.

**Comment by baronfel** [comment]
layout of the new 'core' packages:

```
➜  fslexcorepkg git:(fslexyacc-runtime-dependency) ✗ tree .
.
├── FsLex.Core.nuspec
├── [Content_Types].xml
├── _rels
├── lib
│   └── netstandard2.0
│       ├── FsLex.Core.dll
│       └── FsLex.Core.xml
├── logo.png
└── package
    └── services
        └── metadata
            └── core-properties
                └── b2232bf3fe414660bed7705c1d6d5324.psmdcp

7 directories, 6 files

```

This has only the library dependencies.

**Comment by baronfel** [comment]
layout of the runtime package:

```
➜  bin git:(fslexyacc-runtime-dependency) ✗ tree runtimepkg 
runtimepkg
├── FsLexYacc.Runtime.nuspec
├── [Content_Types].xml
├── _rels
├── lib
│   └── netstandard2.0
│       ├── FsLexYacc.Runtime.dll
│       └── FsLexYacc.Runtime.xml
├── logo.png
└── package
    └── services
        └── metadata
            └── core-properties
                └── df5300db622642b78b0a13ab5c2bd42f.psmdcp

7 directories, 6 files
```

this only has the library, as expected.

**Comment by baronfel** [comment]
@sergey-tihon mind taking a look at these layouts and double-checking to make sure they're what you expect? I think I've got them right now.

**Comment by baronfel** [comment]
Friendly ping for review :)

**Comment by sergey-tihon** [comment]
It looks OK, so I decided to merge it with current master and release as beta/prerelease package to test it.
And it looks like I found one more issue with dependencies versions.

Package version is `11.0.0-beta1` and converted following constrain __`>= 11.0.01`__

`FsLexYacc` is generated with following dependencies
```
Dependencies:
  FsLexYacc.Runtime: '>= 11.0.01 && < 11.1.0'
  FSharp.Core: '>= 4.6.2'
```
`FsLex.Core` & `FsYacc.Core` looks like
```
Dependencies:
  .NETStandard2.0:
    FsLexYacc.Runtime: '>= 11.0.01'
    FSharp.Core: '>= 4.6.2'
```

@baronfel do you know how to fix it? Constrain to `>=11.0.0` instead of `>= 11.0.01`

**Comment by baronfel** [comment]
The difference there is probably because FsLexYacc is built using the older paket.template mechanism, whereas the two new packages are built using `dotnet pack` (which pulls in paket to modify a NuGet-generated nuspec). We can manually specify dependencies and versions in the paket.template file, but that's not currently being done so I'm kinda confused as to where that dependencies group is even coming from. I'll dig into it.

**Comment by baronfel** [comment]
Another thing I see here is that the generated condition of '>= 11.0.01' for the `FsLexYacc.Runtime` dependency won't work at all, because only a prerelease version of that package has been created, right?

**Comment by baronfel** [comment]
Ok, how's this look?

image

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>FsLexYacc</id>
    <version>11.0.0-beta1</version>
    <authors>Microsoft Corporation,Don Syme,F# Software Foundation contributors</authors>
    <owners></owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <licenseUrl>https://github.com/fsprojects/FsLexYacc/blob/master/LICENSE.txt</licenseUrl>
    <projectUrl>https://github.com/fsprojects/FsLexYacc</projectUrl>
    <iconUrl>https://raw.githubusercontent.com/fsprojects/FsLexYacc/master/docs/files/img/logo.png</iconUrl>
    <description>Tools for FsLex/FsYacc lexer/parser generation tools</description>
    <summary>Tools for FsLex/FsYacc lexer/parser generation tools</summary>
    <releaseNotes>Break out core domain logic and generation into core libraries #144
Update FsLexYacc.targets #149
Avoid copying a string twice in LexBuffer.FromString. #150
Fix misc packaging issues #145</releaseNotes>
    <tags>F# fsharp yacc fsyacc lex parsing lexing fslex</tags>
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="FsLexYacc.Runtime" version="11.0.0-beta1" />
        <dependency id="FSharp.Core" version="4.6.2" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by sergey-tihon** [comment]
Sorry, it is a bug in VS Code extension [NuGet NuPkg Viewer](https://marketplace.visualstudio.com/items?itemName=eridem.vscode-nupkg). Dependencies looks OK in NuGet Package Explorer.

**Comment by baronfel** [comment]
Lovely, thank you! Now to rebase the Ranges PR and get that in :)

**Comment by sergey-tihon** [comment]
I've uploaded all `11.0.0-beta1` packages to NuGet, so you can already play with [FsLex.Core](https://www.nuget.org/packages/FsLex.Core/11.0.0-beta1) and [FsYacc.Core](https://www.nuget.org/packages/FsYacc.Core/11.0.0-beta1)

**Comment by sergey-tihon** [comment]
I can confirm that `beta1` not completely broken version ;) and still works as expected https://github.com/sergey-tihon/Tiger/pull/4

**Comment by baronfel** [comment]
When I read 'I can confirm' my heart started sinking! You got me in the first half, not gonna lie 😂

**Pull request merged**
