### PR TITLE
Make the output of fsyacc compatible with nullable reference types.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**

### CODE REVIEW

**Comment by nojaf** [comment]
This does not force people to use NRT right?

**Comment by teo-tsirpanis** [comment]
It does not.

**Comment by nojaf** [comment]
Gotcha, would you like a new version of your changes?
If so, please add an entry in https://github.com/fsprojects/FsLexYacc/blob/master/RELEASE_NOTES.md.
I think we can go with a revision here.

**Comment by teo-tsirpanis** [comment]
I don't immediately need a new release, thanks.

**Review by nojaf — APPROVED** [review]

**Pull request merged**
