### PR TITLE
Netcore Preview3

### PR DESCRIPTION
**Pull request by cloudRoutine**
setup netcore builds for fslex, fsyacc, & fslexyacc.runtime for preview3 with new fsproj format

### CODE REVIEW

**Comment by cloudRoutine** [comment]
@enricosada could you help me get the CI working on this? 
Weren't you working on cli extensibility tools for fslex and fsyacc? It'll only be a small amount of setup on top of this if you still want to do that.

**Comment by enricosada** [comment]
sure, let me check

**Comment by enricosada** [comment]
@cloudRoutine about cli tool, i think is going to be a `FsSrGen` item like before now with new msbuild based `preview3`, so the `dotnet fssrgen` is not that useful.

**Comment by enricosada** [comment]
@cloudRoutine what's the issue with ci? travis fake failure?

**Comment by cloudRoutine** [comment]
@enricosada yup Travis thwarts me once again. 

There were a bunch of commits of me trying to get Travis working but I squashed them 😉

**Comment by ncave** [comment]
@cloudRoutine @enricosada Is it just CI holding this back, or does it need to be updated to netstandard 2.0? How about a tooling version (dotnet-fslexyacc)? Just asking if I can help with something.

**Comment by enricosada** [comment]
@ncave atm is just missing some  ❤️   i'll try to move it forward, need just a refresh of fake script

no, leave `netstandard2.0` aside. is preview (bleeding edge) and should not be used (IHMO) unless really needed for api surface, until is rtm.

about `dotnet fssrgen` ihmo is not that useful anymore. 
was good in `project.json` era, but now is better to maintain only the msbuild task, and remove the `dotnet fssrgen`

this for multiple reasons:

1. msbuild task is easier to use becase can be now (with msbuild15) bundled target+.dll in a single package, who will add it just reference it as packagereference/paketref
2. incremental build
3. faster, no need to spawn process

the 1 was the annoying part with old sdk, but is not really smooth in new one


so i'll try to refresh it

**Comment by ncave** [comment]
@enricosada Thanks.
To clarify, I was asking not about `dotnet-fssrgen` (that's already available for netcore1.0/1.1 and very useful), but `dotnet-fslexyacc`. But I get your point about the task being better, thanks.

**Comment by dsyme** [comment]
Closing this old PR

**Pull request closed without merging**
