### PR TITLE
Walk-through documentation for example JSON parser

### PR DESCRIPTION
**Pull request by belczyk**
I wrote a walk-through documentation for example JSON parser.
Should I PR also docs release?

It will be probably tough PR for you but I think it will be quite valuable. 
Feel free to point out unclear areas, typos, grammar mistakes etc.

### CODE REVIEW

**Comment by brodyberg** [comment]
Very cool, I'll take a look.

**Comment by kkm000** [comment]
@belczyk, sorry I did not mean to intimidate you with the deluge of comments. What I think we should do is just commit this as is, and then either you or someone else would take on improvements. So I'm just accepting this, but a second reading would certainly benefit the piece.

**Comment by belczyk** [comment]
@kkm000 Argh, sorry I forgot about this PR and changes to make, your comments were quite good, I'm moving from New Zealand back to Europe and it's crazy time. I have a bit time today and tomorrow let me go through your comments. Thanks a lot and sorry again.

**Comment by kkm000** [comment]
Absolutely take your time. No worries. Please do not rush it at the expense
of your personal time. Moving is hard, I know!

On Mon, Mar 16, 2015 at 3:01 PM, Sebastian Belczyk <notifications@github.com

**Pull request merged**
