### PR TITLE
Reduction info by the name rather than by the number

### PR DESCRIPTION
**Pull request by mrgleba**

### CODE REVIEW

**Comment by kkm000** [comment]
LGTM, thanks. I do not think we test error messages--I am assuming you verified this working, should be safe to merge, correct?

**Comment by mrgleba** [comment]
I've enhanced reporting even further.
Now we get a really insightful error report (rules their precedences, explicit rule in case of reduce) and the reason to choose one onve the other.
For example:

shift/reduce error at state 5 on terminal ELSE between {[explicit nonassoc 10000] shift(6)} and {noprec reduce(stmt:'IF' expr stmt)} - assuming the former because we preffer shift when unable to compare precedences

This should be safe to commit. I've used more or less a copy of the existing functions to procude the .output file.

**Comment by kkm000** [comment]
Great! Merging.

**Comment by dsyme** [comment]
Nice job, thanks!

**Pull request merged**
