### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by enricosada**
build on osx/linux with travisci

fix test on windows

### CODE REVIEW

**Comment by dsyme** [comment]
Mono Linux doesn't come with Profile 7/78/259 assemblies for FSharp.Core as yet (I've asked Xamarin to add them).  You might need to add a nuget package reference to FSharp.Core to get those.  That would be a good thing to add anyway

**Comment by enricosada** [comment]
thx @dsyme i'll try. It's ok if is .net 3.5 and FSharp.Core 3.1?

Atm linux build it's stuck with path of FsLex.exe in lkg, strange, mac osx msbuild works ok

**Comment by dsyme** [comment]
> thx @dsyme i'll try. It's ok if is .net 3.5 and FSharp.Core 3.1?

yes, or .net 4.0 is ok too I suppose

**Comment by enricosada** [comment]
ok ready to merge

**Pull request merged**
