### PR TITLE
Make FSharp.Core >= LOCKEDVERSION

### PR DESCRIPTION
**Pull request by fangyi-zhou**
As suggested in https://github.com/fsprojects/FsLexYacc/issues/96#issuecomment-483789649

### CODE REVIEW

**Comment by fangyi-zhou** [comment]
Can we get this merged?

**Comment by sergey-tihon** [comment]
@fangyi-zhou  I think yes... but let me check

@dsyme  Is there any reason why 9.0.3 and 9.1.0 are not pushed to NuGet?

**Comment by fangyi-zhou** [comment]
bump bump

**Comment by mrgleba** [comment]
Also bump bump :)

**Comment by dsyme** [comment]
> @dsyme Is there any reason why 9.0.3 and 9.1.0 are not pushed to NuGet?

My apologies, I didn't spot the notifications for these

@sergey-tihon Do you have permission to publish the packges?

**Comment by sergey-tihon** [comment]
Yes, I do

**Comment by sergey-tihon** [comment]
Version [9.1.0](https://www.nuget.org/packages/FsLexYacc/9.1.0) is published on NuGet

**Pull request merged**
