### PR TITLE
Add more complex example of FsLex and FsYacc. Example is parsing valid JSON

### PR DESCRIPTION
**Pull request by belczyk**
New test project containing more complex lexer an parser. Example is using FsLexYacc to parse valid JSON. 

I will contribute comprehensive 'walk through' page for this example in separate PR.

### CODE REVIEW

**Comment by brodyberg** [comment]
What a great idea! I look forward to reading through this. Thanks!

**Comment by kkm000** [comment]
Thanks for the contribution, this is indeed a great demonstration of lex and yacc parsing powers!

**Comment by belczyk** [comment]
Good stuff, nice catches, I will sit on it next morning.

**Comment by belczyk** [comment]
Generated files has been removed in this commit "remove generated files in json example and add gitignore to avoid committing these files". I'm not too sure why they still appear in PR.

**Comment by kkm000** [comment]
@belczyk: Thanks for the fixes! There were 6 generated files in your original PR, 3 are still there in the directory `tests/LexAndYaccMiniProject/`. You might also as well copy your new `.gitignore` to that directory as well, so they won't sneak in by mistake any more!

**Comment by belczyk** [comment]
@kkm000  argh, I checked only my dir ... three times ;p. Now removed. Also gitignore copied.

**Comment by belczyk** [comment]
There is a test failing on AppVeyor, I can't find a reason why my code is breaking it, do you have any ideas ?

**Comment by sergey-tihon** [comment]
@belczyk It may be not your changes. Old [FsYacc tests](https://github.com/fsprojects/FsLexYacc/blob/master/tests/fsyacc/OldFsYaccTests.fsx) are not stable on AppVeyor. I remember that was a problem with line-ending, buy i thought that it was fixed

BTW, you can find more samples here https://github.com/jack-pappas/facio-examples

**Comment by kkm000** [comment]
@belczyk: LGTM, thanks!

**Comment by belczyk** [comment]
Sweet, now it's time to build docs based on that

**Comment by belczyk** [comment]
@brodyberg @kkm000 I want write docs for this example and I wonder how do you create this fancy FSharp snippets in your docs ? I noticed it's even showing tooltips with type info. Is this some kind of VS plugin ?

**Comment by kkm000** [comment]
@belczyk, thanks, I appreciate your contribution! Unfortunately, I am a new guy here, and I have no idea how to create these fancy snippets. I was wondering too. @brodyberg, can you help please?

**Comment by brodyberg** [comment]
@kkm000 You are doing great for "new guy" :-)

@belczyk Can you link to a page with an example of what you are talking about?

**Comment by belczyk** [comment]
@brodyberg  for example here: http://fsprojects.github.io/FsLexYacc/fslex.html

I mean this code snippets with dark background. This is a screenshot: 
http://belczyk.com/code.jpg

**Comment by brodyberg** [comment]
That's interesting - they look pretty cool but I don't see them on OS X
using Chrome. As for how they are done, what I would do is check out the
'gh-pages' branch of the repo and investigate that possibly in combination
with GitHub Pages.

**Comment by kkm000** [comment]
If you look [here](https://github.com/fsprojects/FsLexYacc/commits/gh-pages/fslex.html), the comments say the documentation was autogenerated. I cannot find any sources in the repository.

@sergey-tihon, really need your help here!

**Comment by sergey-tihon** [comment]
Sure, I can help. All docs are stores in [docs/content](https://github.com/fsprojects/FsLexYacc/tree/master/docs/content) folder.
All you need is to created `.md` or `.fsx` file and write everything inside.
More detailed guide you can find [here](http://fsprojects.github.io/ProjectScaffold/writing-docs.html)

Build script has two targets related to document `build GenerateDocs` that rebuild everything in `docs/output` folder and `build ReleaseDocs` that push your changes to `gh-pages` GitHub branch.

If you have a questions about syntax of `.md` / `.fsx` files - I recommend you to visior [FSharp.Formatting](http://tpetricek.github.io/FSharp.Formatting/) site for detailed documentation.

It should be enough to start, but if you want a better VS experience you can try [Elucidate](https://visualstudiogallery.msdn.microsoft.com/2fc5ccff-f424-4721-ac3f-bb9d4ca7de03).

**Comment by belczyk** [comment]
@sergey-tihon  Sweet Thanks, this what I was looking for

**Pull request merged**
