### PR TITLE
Add --module and --internal to FsLex

### PR DESCRIPTION
**Pull request by fangyi-zhou**
Copying code from FsYacc to provide more consistency for FsLex and FsYacc

### CODE REVIEW

**Comment by dsyme** [comment]
Nice work

**Comment by dsyme** [comment]
Looks like Travis is broken
```
     1>/home/travis/.dotnet/sdk/2.1.403/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/travis/build/fsprojects/FsLexYacc/src/FsLex/FsLex.fsproj]
```
We should really move to no longer require Mono as part of the build

**Comment by fangyi-zhou** [comment]
Does targetting net45 solve the Travis issue?

**Comment by fangyi-zhou** [comment]
I've made relevant updates to the docs.
By the way, the website seems to be out of sync with the docs.
https://fsprojects.github.io/FsLexYacc/fslex.html still has references to Microsoft.FSharp.Text.Lexing, which is renamed to FSharp.Text.Lexing

**Comment by dsyme** [comment]
Yes, I'm having a heck of a time trying to work out what "modern" doc generation should look like for F# projects.  See https://github.com/fsprojects/FSharp.Formatting/issues/490 for example.  

Don't worry about it too much just now, it's a long saga that ill take a while to solve

**Comment by dsyme** [comment]
Merging despite the CI failures - working on those in #92

**Pull request merged**
